### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by zehnzwanzig** [zehnzwanzig/PokemonGo_CSV#1]
- [ ] Some sprites are missing
  - [ ] #412 Burmy
  - [ ] #413 Wormadam
  - [ ] #413A Wormadam
  - [ ] #413B Wormadam
  - [ ] #422 Shellos
  - [ ] #423 Gastrodon
  - [ ] #438 Bonsly
  - [ ] #449 Hippopotas
  - [ ] #450 Hippowdon
  - [ ] #465 Tangrowth
  - [ ] #469 Yanmega
  - [ ] #479 Rotom
  - [ ] #479A Rotom
  - [ ] #479B Rotom
  - [ ] #479C Rotom
  - [ ] #479D Rotom
  - [ ] #479E Rotom
  - [ ] #490 Manaphy
  - [ ] #492A Shaymin
  - [ ] #493 Arceus
- [ ] List of attacks are missing
- [ ] Find a good way to integrate needed items or actions for evolving (ex walk 20km with your buddy, kingstone, ...)
